### ISSUE TITLE
Failing to deploy the app to Azure Spring Apps

### ISSUE THREAD

**Issue by v-jiaodi** [spring-guides/gs-spring-boot-for-azure#21]
**Describe the issue:**
When executing `./mvnw azure-spring-apps:deploy` according to [README.md](https://github.com/tataraba/musicbinder-azd#readme), the error is as follows:

![image](https://github.com/spring-guides/gs-spring-boot-for-azure/assets/80496810/b0280eec-f908-4b7e-b89b-fb83d3e5a685)

**Repro Steps:**
1. Create `Azure Spring Apps` in portal.
2. Clone code to local and switch to `complete` folder.
3. Config the web app:
```
export MAVEN_OPTS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED"
./mvnw com.microsoft.azure:azure-spring-apps-maven-plugin:1.14.0:config -DadvancedOptions
```
4. Deploy the app: `./mvnw azure-spring-apps:deploy`

**Environment:**
- OS: Windows desktop.

**Expected behavior:**
 Deploying the app can pass.

 @hemarina for notification.

**Comment by yiliuTo** [comment]
@v-jiaodi thanks for helping testing the readme, could you change the version of maven plugin version from 1.14.0 to 1.18.0 and then rerun the deploy command?
that's to say, you can rerun the command `./mvnw com.microsoft.azure:azure-spring-apps-maven-plugin:1.18.0:config -DadvancedOptions`, then run `./mvnw azure-spring-apps:deploy` and see if the error still exists

**Comment by yiliuTo** [comment]
will update the version in https://github.com/spring-guides/gs-spring-boot-for-azure/pull/24

**Comment by yiliuTo** [comment]
hi @v-jiaodi , now that pr #24 has been merged, could you double check and see if this issue can be closed? thanks
