### ISSUE TITLE
Wrong link address

### ISSUE THREAD

**Issue by v-jiaodi** [spring-guides/gs-spring-boot-for-azure#22]
**Describe the issue:**
Link address error, there are redundant symbols `)`：

![image](https://github.com/spring-guides/gs-spring-boot-for-azure/assets/80496810/f15bcf28-5e51-4d71-adaf-39c09190bb15)

**Suggestion:**
Remove `)` in the link address.

 @hemarina for notification.

**Comment by yiliuTo** [comment]
thanks @v-jiaodi , will update the content in https://github.com/spring-guides/gs-spring-boot-for-azure/pull/24

**Comment by yiliuTo** [comment]
hi @v-jiaodi , now that pr #24 has been merged, could you double check and see if this issue can be closed? thanks
