### ISSUE TITLE
Link document does not match description

### ISSUE THREAD

**Issue by v-jiaodi** [spring-guides/gs-spring-boot-for-azure#23]
**Describe the issue:**
Link documents using `Azure CLI` instead of `Azure Developer CLI(azd)`：

![image](https://github.com/spring-guides/gs-spring-boot-for-azure/assets/80496810/42d0b2ae-bb71-4d6a-930f-df9b1f561322)

**Suggestion:**
Update the link address to point to `azd` related documents.

 @hemarina for notification.

**Comment by yiliuTo** [comment]
Thanks @v-jiaodi , the link document current doesn't contain azd content, but there is a PR to update that doc with AZD: https://github.com/MicrosoftDocs/azure-docs-pr/pull/239541, this is the preview version: https://review.learn.microsoft.com/en-us/azure/spring-apps/quickstart?branch=pr-en-us-239541&tabs=Azure-Developer-CLI%2CAzure-CLI&pivots=sc-standard

**Comment by v-jiaodi** [comment]
After merging with https://github.com/MicrosoftDocs/azure-docs-pr/pull/239541, we will close this issue.

**Comment by yiliuTo** [comment]
@v-jiaodi I will close this issue since the blocking PR has been merged. Feel free to reopen it if you have any other questions.
