### ISSUE TITLE
content outdated

### ISSUE THREAD

**Issue by yucwan** [spring-guides/gs-spring-boot-for-azure#6]
Hi there,

I'm a PM from Java on Azure team and would like to help improve this article. 

The content of this article is outdated and the [repo](https://github.com/microsoft/gs-spring-boot) used is no longer under maintenance. The workflow has changed a lot and users can now achieve the same with following command:
```
git clone https://github.com/spring-projects/spring-petclinic.git
cd spring-petclinic
./mvnw package

mvn com.microsoft.azure:azure-webapp-maven-plugin:1.8.0:config
mvn azure-webapp:deploy
```

A similar docs can be found [here](https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin). 

BRs,
Yuchen

**Comment by dsyer** [comment]
Thanks for the input. I guess we have a choice: we can fix it, or just delete it, and rely on the (excellent) Azure docs. If you would prefer to leave some content here, to help Spring users find the Azure docs, that's fine. Maybe you can send a PR to fix the content?

**Comment by yucwan** [comment]
Hi @dsyer, thanks for your advice. I submitted a PR fixing the content and putting a link to Azure docs in the very beginning. Hope this works.
